site_name: pynarrator
site_url: https://denisabd.github.io/narrator/
nav:
    - Home: index.md
    - Descriptive: descriptive.md

theme: 
    name: material
    highlightjs: true

plugins:
  - search
  - mkdocstrings:
        default_handler: python
        module_name: pynarrator