site_name: pynarrator
site_url: https://denisabd.github.io/narrator/
nav:
    - Home: index.md
    - Reference: reference.md
    - Descriptive: descriptive.md

theme: 
    name: readthedocs
    highlightjs: true
